### ISSUE TITLE
Change cursor to "pointer" when hovering over host

### ISSUE THREAD

**Issue by cirne** [newrelic/nr1-event-stream#6]
hostname is clickable, adds to filter. Make the cursor a pointer on hover. Something like:

```css 
td.clickable hover {
  cursor: pointer; 
}
```
